### ISSUE TITLE
Implement proper time proportioning control and calibration

### ISSUE THREAD

**Issue by TranNicholas** [TranNicholas/svm32#1]
The current PID implementation doesn't actually do the time proportioning stuff e.g. windowStart is not shifted and windowSize has no effect. Somehow it still works and is loosely based on https://playground.arduino.cc/Code/PIDLibraryRelayOutputExample/

# Todo
- [ ] Time Proportioning PID
- [ ] Add a feature to manipulate Kp, Ki, Kd
- [ ] Auto calibration feature

# References
- https://playground.arduino.cc/Code/PIDLibraryRelayOutputExample/
- https://github.com/br3ttb/Arduino-PID-Library/blob/master/examples/PID_RelayOutput/PID_RelayOutput.ino
